CREATE TABLE IF NOT EXISTS product_inventory (
  product_id INTEGER PRIMARY KEY,
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS product_inventory_stock_idx ON product_inventory(stock);

INSERT OR IGNORE INTO product_inventory (product_id, stock, updated_at) VALUES
  (1,12,CURRENT_TIMESTAMP),(2,9,CURRENT_TIMESTAMP),(3,20,CURRENT_TIMESTAMP),(4,7,CURRENT_TIMESTAMP),(5,11,CURRENT_TIMESTAMP),
  (6,14,CURRENT_TIMESTAMP),(7,6,CURRENT_TIMESTAMP),(8,10,CURRENT_TIMESTAMP),(9,8,CURRENT_TIMESTAMP),(10,13,CURRENT_TIMESTAMP),
  (11,15,CURRENT_TIMESTAMP),(12,5,CURRENT_TIMESTAMP),(13,9,CURRENT_TIMESTAMP),(14,12,CURRENT_TIMESTAMP),(15,4,CURRENT_TIMESTAMP),
  (16,11,CURRENT_TIMESTAMP),(17,8,CURRENT_TIMESTAMP),(18,16,CURRENT_TIMESTAMP),(19,6,CURRENT_TIMESTAMP),(20,10,CURRENT_TIMESTAMP),
  (21,7,CURRENT_TIMESTAMP),(22,9,CURRENT_TIMESTAMP),(23,5,CURRENT_TIMESTAMP),(24,12,CURRENT_TIMESTAMP),(25,8,CURRENT_TIMESTAMP),
  (26,4,CURRENT_TIMESTAMP),(27,6,CURRENT_TIMESTAMP),(28,14,CURRENT_TIMESTAMP),(29,10,CURRENT_TIMESTAMP),(30,9,CURRENT_TIMESTAMP);
